### ISSUE TITLE
Help for connecting to datasource behind proxy

### ISSUE THREAD

**Issue by harshu108** [strongloop/loopback-example-connector#2]
I am trying to connect to a REST data source northwind and my system resides behind secured network. How do I add proxy settings?

**Comment by richardpringle** [comment]
Hey @harshu108, please ask in one (or more) of the following communities:
- [Google Groups](https://groups.google.com/forum/#!forum/loopbackjs)
- [StackOverflow](http://stackoverflow.com/questions/tagged/loopbackjs+or+strongloop?sort=newest&pageSize=50)
- [Gitter](https://gitter.im/strongloop/loopback) (supported, but we prefer posting to Google Groups so others may benefit from the discussions)

Hopefully you will get a more timely response as well!

We are reserving the issues section on GitHub for bug reports and feature requests only, so I will close this issue. If you do not find any answers in the communities mentioned above, please open a detailed feature request in the most relevant location (probably [loopback-connector-rest](https:github.com/strongloop/loopback-connector-rest) in this case).

As I said, I am closing the issue but please feel free to comment in here to carry on the discussion with me. 

Good luck and happy coding!
