### ISSUE TITLE
LB4 Version?

### ISSUE THREAD

**Issue by payne-chris-r** [strongloop/loopback-example-connector#20]
### Bug or feature request

- [ ] Bug
- [x] Feature request

### Description of feature (or steps to reproduce if bug)

I'm hoping to see an lb4 version of connecting to an external API, but I can't find any on the internet... 😢

**Comment by aitorjs** [comment]
Could help! :-D https://loopback.io/doc/en/lb4/Calling-other-APIs-and-web-services.html

**Comment by payne-chris-r** [comment]
booyah--thanks!
